### ISSUE TITLE
PytestDeprecationWarning regarding DescribeBlock with pytest 5.4

### ISSUE THREAD

**Issue by Cito** [pytest-dev/pytest-describe#26]
With the latest pytest 5.4 I start getting the following warnings:
```
.tox/py36/lib/site-packages/pytest_describe/plugin.py:149: PytestDeprecationWarning:
  direct construction of DescribeBlock has been deprecated,
  please use DescribeBlock.from_parent return DescribeBlock(obj, collector)
```

**Comment by Cito** [comment]
Note that there are also warnings like `PytestDeprecationWarning: TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw`, but I think this is a [pytest issue](https://github.com/pytest-dev/pytest/issues/6936).

**Comment by Cito** [comment]
See also [the 5.4 list of deprecations](https://docs.pytest.org/en/5.4.0/changelog.html#deprecations) regarding this change.

**Comment by ropez** [comment]
@Cito Unfortunately, I haven't programmed I python in almost three years. If anyone is able to submit a PR, I will be happy to create a new version, but I'm afraid I won't have time to resolve these issues myself.

**Comment by Cito** [comment]
Too bad. But thank you for the feedback. Sadly, I cannot help either - too many other things going on already, and I fear this needs some deep diving into pytest plugin programming.

Please, if anybody else can help out here, that would be great.

**Comment by jacebrowning** [comment]
I can take a look this weekend.

**Comment by jacebrowning** [comment]
@ropez It's not a complete blocker, but getting https://github.com/ropez/pytest-describe/pull/25 merged first will make fixing this warning easier.

**Comment by jacebrowning** [comment]
https://github.com/ropez/pytest-describe/pull/27 contains the patch.

I've confirmed this eliminates the `PytestDeprecationWarning`, by installing the patch into a couple of my projects.

**Comment by ropez** [comment]
@Cito @jacebrowning Would it be possible for any of you to just take over the responsibility for this? It has been just working for several years, so it's not really much to do, except for the occasional compatibility issue.

**Comment by Cito** [comment]
You mean the responsibility for the whole project? Including releasing on PyPI or would you still do that?

**Comment by ropez** [comment]
Yes, I meant the whole project. I'm sure it's possible to add access to PyPi.

**Comment by Cito** [comment]
Yes, you can simply add new owners or maintainers (who can only publish but not delete releases) on PyPI. Regarding GitHub, it's probably best to transfer the project to the [pytest-dev](https://github.com/pytest-dev) organization instead to another person. The current repository address  ropez/pytest-describe will then be automatically forwarded by GitHub to pytest-dev/pytest-describe. I guess it's best to ask on pytest-dev@python.org if they can initiate the transfer. Do you want to do that or shall I ask on your behalf? I can take over maintenance if nobody else volunteers,  since I would hate to see this project die, but if @jacebrowning or somebody on the pytest-dev mailing list volunteers, or we could share the responsibility, I would be happier.

**Comment by jacebrowning** [comment]
I'm not yet part of the **pytest-dev** organization, but I'm willing to help make releases if we can get it transferred there.

**Comment by ropez** [comment]
@Cito Sounds great! I would be very happy if you could initiate this. I also wouldn't like to see this die, even if I'm not able to maintain it.

**Comment by Cito** [comment]
We now got a +1 from a pytest-dev developer, who also pointed to the official documentation for [submitting plugins to pytest-dev](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#submitting-plugins-to-pytest-dev), but we need another +1 to initiate the transfer.

You will also need to make @jacebrowning and me additional maintainers on PyPI, so that we have the minimum number of 3 people who can publish releases.

**Comment by Cito** [comment]
@ropez We now have two +1 from pytest-dev, so looks like we can start the transfer.

I have created a separate issue #30 to track the progress of the transfer, let's move this discussion there.
