### ISSUE TITLE
Transfer repository to pytest-dev

### ISSUE THREAD

**Issue by Cito** [pytest-dev/pytest-describe#30]
As discussed in #26, it was decided to move the repository to pytest-dev.

@jacebrowning and @Cito volunteered to act as maintainers to help @ropez keep the project alive.

We have the necessary two +1 from pytest-dev developers to start the transfer.

The process is described here: [Submitting Plugins to pytest-dev](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#submitting-plugins-to-pytest-dev)

I have created this issue to track the transfer and #28 and #29 to fulfill some missing requirements.

**Comment by Cito** [comment]
Inviting @flub (Floris) from pytest-dev to help with the transfer.

As far as I see the next action is that @ropez adds Jace and me as maintainers on PyPI and transfers ownership of the project on GitHub to @flub who would then move the project to pytest-dev.

**Comment by ropez** [comment]
@Cito @jacebrowning What are your usernames on PyPi? It seems like I need to enter this manually.

**Comment by ropez** [comment]
I took a chance on the same usernames that you have here, and the profile images seems to match, to I guess that is correct.

**Comment by flub** [comment]
I've moved the repo to pytest-dev now, thanks for transferring it to me @ropez.  Both @Cito and @jacebrowning should have invites to the admin and developer teams, once you accept you should be able to adjust permissions, members etc yourself.  Let me know if any of this didn't work out or you need anything else from me.

Welcome to pytest-dev!

**Comment by flub** [comment]
Btw, if you feel like adding nicoddemus, ronny, flub, hpk or some subset of us to pypi (those are the pypi usernames) please do so as well.  Not majorly important as you are already two though.

**Comment by ropez** [comment]
@flub I added you as Owner on PyPi

**Comment by ropez** [comment]
@Cito @jacebrowning

Thank you guys for doing this. It makes me proud that this little thing that I created for my own use years ago, is still being used.

**Comment by Cito** [comment]
@ropez Thanks for creating this project in the first place. I think the reasons why you created it are still valid so it's still as useful.

@flub Thanks a lot for helping with this so quickly.

@jacebrowning @ropez I have created #31 to discuss the next steps.

**Comment by ropez** [comment]
@Cito @flub I'm trying to do it, but I actually haven't been logged in to Pypi for years, and I'm having some issues with that. If you can do it, please go ahead.

**Comment by Cito** [comment]
@ropez @flub Thanks a lot for the quick response. I was able to set up the trusted publishing and 3.0.0 is already published that way.

Shall I remove the existing PYPI_TOKEN? It is not referenced in the GitHub action any more.

**Comment by flub** [comment]
Seems like @ropez succeeded already.  And yes, remove any unused tokens.
