### ISSUE TITLE
Roadmap for version 1 and 2

### ISSUE THREAD

**Issue by Cito** [pytest-dev/pytest-describe#31]
I have created this issue to discuss the next releases and versioning policy.

My suggestion is to create first a version 1.0 that will support Py 2.7 + 3.5 - 3.8 and pytest 2.x - 5.x, for those who need to test legacy software.

After 1.0 has been released, we immediately publish a version 2.0 that will require Python 3.6+ and newer pytest versions. This will allow to simplify and clean the code and reduce the maintenance burden.

If everybody agrees, I will publish such a 1.0 release this weekend and start working on 2.0.

**Comment by jacebrowning** [comment]
I agree with the caveat that I don't think we can simultaneously support Python 2 and pytest 5: https://docs.pytest.org/en/latest/py27-py34-deprecation.html

> For those reasons, in Jun 2019 it was decided that pytest 4.6 series will be the last to support Python 2.7 and 3.4.

In my opinion, the current codebase is sufficient to test legacy software so we should clean up the documentation to explicitly call out supported versions and call that 1.0, then proceed with 2.0 as you describe.

**Comment by Cito** [comment]
You're right, I will document that. These combinations are already excluded in the Travis test matrix.

For version 2, what versions shall we require? Maybe Python 3.6+ and Pytest 4+?

**Comment by jacebrowning** [comment]
> Maybe Python 3.6+ and Pytest 4+?

That sounds good to me.

**Comment by Cito** [comment]
Hm, shortly after we joined pytest-dev, three of the members left. Not sure what this means :(

**Comment by Cito** [comment]
I have processed all open issues and PRs and want to publish the 1.0 release now.

@jacebrowning - looks good to you or are there any small changes you still want to get into 1.0?

**Comment by jacebrowning** [comment]
@Cito Nope, ship it! 😄

**Comment by Cito** [comment]
Ok, shipped now.

Also created a 1.x branch for possible bugfix releases, and started working on 2.0 in the master branch, as discussed above.

**Comment by Cito** [comment]
After desuppporting the older pytest and Python versions, I have removed now unneeded cruft in the master branch and used newer syntax where possible. In principle, we could already release 2.0, but there are no new features yet. In any case, this step makes maintenance a lot easier.

**Comment by Cito** [comment]
Will leave this open until version 2 has been published.

**Comment by satyanash** [comment]
Any hopes on when v2 will release?
Don't want this lib to die out. Pytest feels unusable without this.

**Comment by Cito** [comment]
Thanks for reminding me, I somehow lost track of this project. Moved this higher up in my todo list now.

**Comment by satyanash** [comment]
Any update on the v2 release @Cito

**Comment by Cito** [comment]
[Version 2.0](https://github.com/pytest-dev/pytest-describe/releases/tag/2.0.0) has been released now.

Sorry all for the long wait. Please open another issue if you have any problems with this version.
